---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r loadingAndPreprocessingTheData, echo=TRUE}
library(ggplot2)
unzip("activity.zip", "activity.csv")
activity <- read.table("activity.csv", sep=",", header=T)
activityNoNA <- activity[!is.na(activity$steps),]
```

## What is mean total number of steps taken per day?
```{r meanTotalSteps, echo=TRUE}
activityByDate <- aggregate(steps ~ date, activityNoNA, sum)
qplot(activityByDate$date, activityByDate$steps, geom="bar", stat="identity")
mean(activityByDate$steps)
median(activityByDate$steps)
```

## What is the average daily activity pattern?
```{r averageDailyActivityPattern, echo=TRUE}
activityByInterval <- aggregate(steps ~ interval, activityNoNA, mean)
qplot(activityByInterval$interval, activityByInterval$steps, geom="line", stat="identity")
activityByInterval[which.max(activityByInterval$steps),]
```

## Imputing missing values
```{r imputingMissingValues, echo=TRUE}
sum(is.na(activity$steps))
activityImputed <- activity
for (i in 1:nrow(activityImputed)) {
    if (is.na(activityImputed[i, 1])) {
       activityImputed[i, 1] <- activityByInterval[activityByInterval$interval == activityImputed[i, 3], 2]
    }
}
activityByDateImputed <- aggregate(steps ~ date, activityImputed, sum)
qplot(activityByDateImputed$date, activityByDateImputed$steps, geom="bar", stat="identity")
mean(activityByDateImputed$steps)
median(activityByDateImputed$steps)
```

## Are there differences in activity patterns between weekdays and weekends?
```{r weekendsAndWeekdays, echo=TRUE}
activityImputed$wend <- as.factor(ifelse(weekdays(as.Date(activityImputed$date)) %in% c("Saturday","Sunday"), "Weekend", "Weekday"))
activityByIntervalWend <- aggregate(steps ~ interval+wend, activityImputed, mean)
qplot(activityByIntervalWend$interval, activityByIntervalWend$steps, data=activityByIntervalWend, geom="line", stat="identity", facets = .~wend)
```
